fix: Unrecognized field "LayerSources"
I just upgraded the jib-gradle-plugin as recommended and the error was
resolved.

```
A new version of jib-gradle-plugin (3.4.5) is available (currently using 3.2.1). Update your build configuration to use the latest features and fixes!
https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/CHANGELOG.md

Please see https://github.com/GoogleContainerTools/jib/blob/master/docs/privacy.md for info on disabling this update check.

Executing tasks:
[===========                   ] 37.5% complete
> processing base image prism-base

> Task :batch:jibDockerBuild FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
9 actionable tasks: 8 executed, 1 up-to-date

* What went wrong:
Execution failed for task ':batch:jibDockerBuild'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Unrecognized field "LayerSources" (class com.google.cloud.tools.jib.docker.json.DockerManifestEntryTemplate), not marked as ignorable (3 known properties: "Config", "RepoTags", "Layers"])
   at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 552] (through reference chain: java.lang.Object[][0]->com.google.cloud.tools.jib.docker.json.DockerManifestEntryTemplate["LayerSources"])
```